### ISSUE TITLE
Error running ICA

### ISSUE THREAD

**Issue by pietrisko** [CompEpigen/DecompPipeline#10]
Hello,

I get this error running ICA:

```
prepare.data(rnb.set = data.prep$rnb.set.filtered,
                          normalization = "none",
                          analysis.name = "POS_samples",
                          filter.beads=FALSE,
                          filter.intensity=FALSE,
                          remove.ICA=TRUE,
                          filter.na = FALSE,
                          filter.context = FALSE,
                          filter.snp = FALSE,
                          filter.sex.chromosomes = FALSE,
                          filter.cross.reactive = FALSE,
                          conf.fact.ICA=c("Sex"),
                          ica.setting=c("alpha.fact"=1e-5,"save.report"=TRUE,
                                        "ntry"=10,"nmin"=20,"nmax"=50,"ncores"=20))

```

<img width="842" alt="image" src="https://user-images.githubusercontent.com/44844060/214627616-971132a4-ebe3-4b7f-a7e4-869cb6dbb654.png">

**Comment by schmic05** [comment]
Hi @pietrisko 

Thanks for using DecompPipeline. Can you describe your dataset in more details? How many samples do you have? If you have less than 26 samples, you cannot compute 26 ICA components. You can set the maximum number of components using the option:
```ica.setting=c(nmin=10, nmax=20)```
Hope that helps,
Michael
