### ISSUE TITLE
Proper release

### ISSUE THREAD

**Issue by seb45tian** [CompEpigen/DecompPipeline#8]
Hi,
would it be possible to create proper releases based on the version specified in `DESCRIPTION` (e.g. at this point `1.0.3`). This would greatly simplify the installation process at our site (via EasyBuild) and improve overall reproducibility of obtained results.

Many thanks!

**Comment by schmic05** [comment]
Hi @seb45tian,
Thanks for the nice suggestion. We just created and published such a release.
