### ISSUE TITLE
Package ‘RefFreeEWAS’ was removed from the CRAN repository

### ISSUE THREAD

**Issue by kohlman** [CompEpigen/DecompPipeline#9]
Hi there,

It seems that RefFreeEWAS was just recently removed from the CRAN repository:

https://cran.r-project.org/web/packages/RefFreeEWAS/index.html

I don't know if or how quickly this issue will be resolved by the respective package authors. Currently, DecompPipeline installation fails due to this problem. Manual installation of RefFreeEWAS from the archive seems to be a fix so far, but I guess this will be an obstacle for non-expert users.

Best,

Axel

**Comment by lutsik** [comment]
Dear Axel, thanks a lot for reporting, we will see what can be done. Kind regards, Pavlo

**Comment by schmic05** [comment]
Hi Axel,

Thanks for reporting. I temporarily removed the RefFreeEWAS dependency until the authors fix the build on CRAN. In the current commit, DecompPipeline does not depend on the package anymore.

Best,

Michael

**Comment by kohlman** [comment]
Alright, sounds good. Thanks for the quick reaction!
